=== legafise/JavaWebDevelopment/jwd-xml/src/main/resources/data/medicines.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified"
        targetNamespace="http://www.training.by/medicine"
        xmlns:tns="http://www.training.by/medicine">
    <element name="medicines">
        <complexType>
            <sequence>
                <element ref="tns:medicine" minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <element name="medicine" type="tns:Medicine" abstract="true"/>
    <element name="original-medicine" type="tns:OriginalMedicine" substitutionGroup="tns:medicine"/>
    <element name="analog" type="tns:Analog" substitutionGroup="tns:medicine"/>

    <complexType name="Medicine">
        <sequence>
            <element name="name" type="string"/>
            <element name="pharm" type="string"/>
            <element name="versions" type="tns:Versions"/>
        </sequence>

        <attribute name="id" use="required">
            <simpleType>
                <restriction base="ID">
                    <pattern value="G-\d{2,8}"/>
                </restriction>
            </simpleType>
        </attribute>

        <attribute name="group" use="required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="antibiotics"/>
                    <enumeration value="vitamins"/>
                    <enumeration value="pain killer"/>
                    <enumeration value="anti-allergic"/>
                    <enumeration value="antiviral"/>
                    <enumeration value="ointment"/>
                    <enumeration value="nasal drops"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <complexType name="Analogs">
        <sequence>
            <element name="analog-name" type="string" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Versions">
        <sequence>
            <element name="version" type="tns:Version"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Version">
        <sequence>
            <element name="certificate" type="tns:Certificate"/>
            <element name="package" type="tns:Package"/>
            <element name="dosage" type="tns:Dosage"/>
        </sequence>
    </complexType>

    <complexType name="Certificate">
        <sequence>
            <element name="number" type="string"/>
            <element name="issue-date" type="date"/>
            <element name="expiry-date" type="date"/>
            <element name="registration-organisation" type="string"/>
        </sequence>
    </complexType>

    <complexType name="Package">
        <sequence>
            <element name="package-type" default="blister">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="blister"/>
                        <enumeration value="jar"/>
                        <enumeration value="spray"/>
                        <enumeration value="ampule"/>
                        <enumeration value="tube"/>
                        <enumeration value="syringe"/>
                        <enumeration value="syrup"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="amount-in-package" type="string"/>
            <element name="price" type="double"/>
        </sequence>
    </complexType>

    <complexType name="Dosage">
        <sequence>
            <element name="dose" type="string"/>
        </sequence>

        <attribute name="medication-frequency" use="optional" default="By doctor's prescription">
            <simpleType>
                <restriction base="string">
                    <enumeration value="Once a day"/>
                    <enumeration value="Twice a day"/>
                    <enumeration value="Three times per day"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <complexType name="Analog">
        <complexContent>
            <extension base="tns:Medicine">
                <sequence>
                    <element name="title-of-original" type="string"/>
                </sequence>
                <attribute name="efficiency" type="double" use="required"/>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="OriginalMedicine">
        <complexContent>
            <extension base="tns:Medicine">
                <sequence>
                    <element name="analogs" type="tns:Analogs"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
</schema>

=== legafise/JavaWebDevelopment/jwd-xml/src/main/resources/data/medicines.xml
<?xml version="1.0" encoding="UTF-8"?>
<medicines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://www.training.by/medicine"
           xsi:schemaLocation="http://www.training.by/medicine medicines.xsd">
    <original-medicine id="G-563" group="ointment">
        <name>Mekol</name>
        <pharm>Aktavis</pharm>
        <versions>
            <version>
                <certificate>
                    <number>b-423</number>
                    <date-of-issue>2021-08-10</date-of-issue>
                    <expiry-date>2023-08-10</expiry-date>
                    <registration-organisation>Minzdrav</registration-organisation>
                </certificate>
                <package>
                    <package-type>tube</package-type>
                    <amount-in-package>50g</amount-in-package>
                    <price>4.35</price>
                </package>
                <dosage>
                    <dose>1g</dose>
                </dosage>
            </version>
        </versions>
        <analogs>
            <analog>Levomekol</analog>
        </analogs>
    </original-medicine>

    <analog id="G-562" group="ointment" efficiency="90.4">
        <name>Levomekol</name>
        <pharm>Aktaves</pharm>
        <versions>
            <version>
                <certificate>
                    <number>b-422</number>
                    <date-of-issue>2021-08-10</date-of-issue>
                    <expiry-date>2023-08-10</expiry-date>
                    <registration-organisation>Minzdrav</registration-organisation>
                </certificate>
                <package>
                    <package-type>tube</package-type>
                    <amount-in-package>60g</amount-in-package>
                    <price>5.2</price>
                </package>
                <dosage>
                    <dose>1g</dose>
                </dosage>
            </version>
        </versions>
        <title-of-original>Mekol</title-of-original>
    </analog>

    <original-medicine id="G-564" group="ointment">
        <name>C-Derm</name>
        <pharm>Evalar</pharm>
        <versions>
            <version>
                <certificate>
                    <number>h-24</number>
                    <date-of-issue>2021-08-10</date-of-issue>
                    <expiry-date>2023-08-10</expiry-date>
                    <registration-organisation>Minzdrav</registration-organisation>
                </certificate>
                <package>
                    <package-type>tube</package-type>
                    <amount-in-package>40g</amount-in-package>
                    <price>7.55</price>
                </package>
                <dosage frequency-of-medication="Once a day">
                    <dose>5mg</dose>
                </dosage>
            </version>
        </versions>
        <analogs>
            <analog>Tri-Derm</analog>
        </analogs>
    </original-medicine>

    <analog id="G-565" group="ointment" efficiency="85.6">
        <name>Tri-Derm</name>
        <pharm>Bayer</pharm>
        <versions>
            <version>
                <certificate>
                    <number>j-53</number>
                    <date-of-issue>2021-08-10</date-of-issue>
                    <expiry-date>2023-08-10</expiry-date>
                    <registration-organisation>Minzdrav</registration-organisation>
                </certificate>
                <package>
                    <package-type>tube</package-type>
                    <amount-in-package>40g</amount-in-package>
                    <price>7.55</price>
                </package>
                <dosage frequency-of-medication="Once a day">
                    <dose>5mg</dose>
                </dosage>
            </version>
        </versions>
        <title-of-original>C-Derm</title-of-original>
    </analog>

    <original-medicine id="G-574" group="nasal drops">
        <name>Otrivin</name>
        <pharm>Consumer</pharm>
        <versions>
            <version>
                <certificate>
                    <number>a-923</number>
                    <date-of-issue>2021-08-10</date-of-issue>
                    <expiry-date>2023-08-10</expiry-date>
                    <registration-organisation>Minzdrav</registration-organisation>
                </certificate>
                <package>
                    <package-type>spray</package-type>
                    <amount-in-package>10ml</amount-in-package>
                    <price>6.3</price>
                </package>
                <dosage frequency-of-medication="Twice a day">
                    <dose>0.2ml</dose>
                </dosage>
            </version>
        </versions>
        <analogs>
            <analog>Snup</analog>
            <analog>Ksilin</analog>
        </analogs>
    </original-medicine>

    <original-medicine id="G-567" group="antibiotics">
        <name>Amoklav</name>
        <pharm>Pharmland</pharm>
        <versions>
            <version>
                <certificate>
                    <number>n-36</number>
                    <date-of-issue>2021-08-10</date-of-issue>
                    <expiry-date>2023-08-10</expiry-date>
                    <registration-organisation>Minzdrav</registration-organisation>
                </certificate>
                <package>
                    <package-type>blister</package-type>
                    <amount-in-package>14</amount-in-package>
                    <price>13.3</price>
                </package>
                <dosage>
                    <dose>1</dose>
                </dosage>
            </version>
        </versions>
        <analogs>
            <analog>Amoksilav</analog>
        </analogs>
    </original-medicine>

    <original-medicine id="G-915" group="antibiotics">
        <name>Enterogermina</name>
        <pharm>Shanofi</pharm>
        <versions>
            <version>
                <certificate>
                    <number>f-241</number>
                    <date-of-issue>2021-08-10</date-of-issue>
                    <expiry-date>2024-08-10</expiry-date>
                    <registration-organisation>Minzdrav</registration-organisation>
                </certificate>
                <package>
                    <package-type>blister</package-type>
                    <amount-in-package>10</amount-in-package>
                    <price>14.54</price>
                </package>
                <dosage frequency-of-medication="Twice a day">
                    <dose>1</dose>
                </dosage>
            </version>
        </versions>
        <analogs>
            <analog>Acidolak</analog>
            <analog>Micerol</analog>
        </analogs>
    </original-medicine>

    <analog id="G-916" group="antibiotics" efficiency="96.4">
        <name>Micerol</name>
        <pharm>Eblolav</pharm>
        <versions>
            <version>
                <certificate>
                    <number>e-715</number>
                    <date-of-issue>2021-08-10</date-of-issue>
                    <expiry-date>2022-08-10</expiry-date>
                    <registration-organisation>Minzdrav</registration-organisation>
                </certificate>
                <package>
                    <package-type>blister</package-type>
                    <amount-in-package>20</amount-in-package>
                    <price>9.75</price>
                </package>
                <dosage>
                    <dose>2</dose>
                </dosage>
            </version>
            <version>
                <certificate>
                    <number>e-718</number>
                    <date-of-issue>2021-08-10</date-of-issue>
                    <expiry-date>2022-08-10</expiry-date>
                    <registration-organisation>Minzdrav</registration-organisation>
                </certificate>
                <package>
                    <package-type>jar</package-type>
                    <amount-in-package>30</amount-in-package>
                    <price>12.3</price>
                </package>
                <dosage>
                    <dose>1</dose>
                </dosage>
            </version>
        </versions>
        <title-of-original>Enterogermina</title-of-original>
    </analog>

    <original-medicine id="G-032" group="anti-allergic">
        <name>Cetrin</name>
        <pharm>Reddis</pharm>
        <versions>
            <version>
                <certificate>
                    <number>h-94</number>
                    <date-of-issue>2021-08-10</date-of-issue>
                    <expiry-date>2023-08-10</expiry-date>
                    <registration-organisation>Minzdrav</registration-organisation>
                </certificate>
                <package>
                    <package-type>blister</package-type>
                    <amount-in-package>15</amount-in-package>
                    <price>11.42</price>
                </package>
                <dosage frequency-of-medication="Twice a day">
                    <dose>1</dose>
                </dosage>
            </version>
        </versions>
        <analogs>
            <analog>Cetirizin</analog>
        </analogs>
    </original-medicine>

    <original-medicine id="G-831" group="antiviral">
        <name>Groprinosin</name>
        <pharm>Gedeon</pharm>
        <versions>
            <version>
                <certificate>
                    <number>e-716</number>
                    <date-of-issue>2021-08-10</date-of-issue>
                    <expiry-date>2023-08-10</expiry-date>
                    <registration-organisation>Minzdrav</registration-organisation>
                </certificate>
                <package>
                    <package-type>blister</package-type>
                    <amount-in-package>50</amount-in-package>
                    <price>32.3</price>
                </package>
                <dosage>
                    <dose>1</dose>
                </dosage>
